### ISSUE TITLE
Add implementation in Rust

### ISSUE THREAD

**Issue by ERnsTL** [msgpack-rpc/msgpack-rpc#79]
There is now an implementation for [MsgPack in Rust](https://github.com/mneumann/rust-msgpack).

Since this here seems to be the central place for MsgPack-RPC libraries, please add implementation in Rust; potentially using the aforementioned encoder/decoder library already present.

Thanks.

**Comment by ids1024** [comment]
Related: mneumann/rust-msgpack#53

**Comment by kuenishi** [comment]
It sounds like there're no code for that regarding mneumann/rust-msgpack#53 . I could make empty repository for that, but who's going to make it?

**Comment by kuenishi** [comment]
It looks like there are more popular implementations in [crate.io](https://crates.io/keywords/msgpack) and the implementation mentioned here isn't up in create.io . So far I feel like rejecting this offer.
